# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160920_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.GameType'),
        ),
        migrations.AlterField(
            model_name='game',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.Map'),
        ),
    ]
