# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='faction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='factions.Faction'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='race',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='races.Race'),
        ),
    ]
