# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0001_initial'),
        ('races', '0001_initial'),
        ('champions', '0002_auto_20160920_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='faction',
        ),
        migrations.AddField(
            model_name='champion',
            name='faction',
            field=models.ManyToManyField(to='factions.Faction'),
        ),
        migrations.RemoveField(
            model_name='champion',
            name='race',
        ),
        migrations.AddField(
            model_name='champion',
            name='race',
            field=models.ManyToManyField(to='races.Race'),
        ),
    ]
