# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0001_initial'),
        ('races', '0001_initial'),
        ('champions', '0003_auto_20160920_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='faction',
        ),
        migrations.AddField(
            model_name='champion',
            name='faction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factions.Faction'),
        ),
        migrations.RemoveField(
            model_name='champion',
            name='race',
        ),
        migrations.AddField(
            model_name='champion',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='races.Race'),
        ),
    ]
